
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/securitysite
    username: ym
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect